using AttendanceMariaDBToOracle.classes;
using Helpers;
using Helpers.classes;
using Helpers.controllers;
using Oracle.ManagedDataAccess.Client;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

namespace AttendanceMariaDBToOracle
{
    internal class OracleDbProcessing
    {
        // This class will handle the processing of data to Oracle DB
        // It will include methods to connect to the database, insert data,
        // and process it as needed for the application.
        DatabaseInfo db;
        string configPath = AppDomain.CurrentDomain.BaseDirectory + "oracle.config";
        string connectionString = string.Empty;
        OracleConnection? connection;

        public ConnectionState ConnectionState
        {
            get
            {
                if (connection == null)
                    return ConnectionState.Closed;
                return connection.State;
            }
        }

        public OracleDbProcessing()
        {
            db = new DatabaseInfo();
            db = Helper.ReadObjectFromFile<DatabaseInfo>(configPath, true);

            //db.Server = "14.224.190.187";
            //db.Database = "SWPROD";
            //db.Port = 1512;
            //db.UserId = "SWPROD";
            //db.Password = "SwProd-2023-NodeJS";
            connectionString = "Data Source=$[Server]:$[Port]/$[Database];User Id=$[UserId];Password=$[Password];";
            connectionString = Helper.ReplaceText(connectionString, db);
            
            // Ensure table exists when initializing
            EnsureTableExists();
            EnsureProcedureExists();
        }

        public bool CheckProcedureExist()
        {
            string sql = $"SELECT COUNT(*) FROM USER_PROCEDURES WHERE OBJECT_NAME = 'HR_PRO_TRANSFER_FROM_ALPETA'";
            using (var connection = new OracleConnection(connectionString))
            {
                connection.Open();
                using (var command = new OracleCommand(sql, connection))
                {
                    var result = command.ExecuteScalar();
                    return Convert.ToInt32(result) > 0;
                }
            }
        }

        private bool CheckTableExists()
        {
            string sql = @"
                SELECT COUNT(*) FROM USER_TABLES 
                WHERE TABLE_NAME = 'THR_TERMINAL_LOGS'
            ";

            try
            {
                using (var connection = new OracleConnection(connectionString))
                {
                    connection.Open();
                    using (var command = new OracleCommand(sql, connection))
                    {
                        var result = command.ExecuteScalar();
                        return Convert.ToInt32(result) > 0;
                    }
                }
            }
            catch (Exception ex)
            {
                LogController.Error($"Error checking table existence: {ex.Message}");
                Console.WriteLine($"Error checking table existence: {ex.Message}"); // For console output
                return false;
            }
        }

        private bool CreateTable()
        {
            string createTableSql = @"
                CREATE TABLE THR_TERMINAL_LOGS (
                    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    TERMINAL_ID NUMBER(10) NOT NULL,
                    USER_ID NUMBER(10) NOT NULL,
                    USER_NAME VARCHAR2(100),
                    CARD_ID VARCHAR2(50),
                    EVENT_TIME DATE NOT NULL,
                    AUTH_TYPE NUMBER(5) DEFAULT 0,
                    AUTH_RESULT NUMBER(5) DEFAULT 0,
                    CREATED_DATE DATE DEFAULT SYSDATE
                )
            ";

            string createIndexSql = @"
                CREATE INDEX IDX_THR_TERMINAL_LOGS_TIME ON THR_TERMINAL_LOGS (EVENT_TIME)
            ";

            try
            {
                using (var connection = new OracleConnection(connectionString))
                {
                    connection.Open();
                    using (var transaction = connection.BeginTransaction())
                    {
                        try
                        {
                            // Create table
                            using (var command = new OracleCommand(createTableSql, connection))
                            {
                                command.Transaction = transaction;
                                command.ExecuteNonQuery();
                            }

                            // Create index
                            using (var command = new OracleCommand(createIndexSql, connection))
                            {
                                command.Transaction = transaction;
                                command.ExecuteNonQuery();
                            }

                            transaction.Commit();
                            LogController.Information("Successfully created THR_TERMINAL_LOGS table and index.");
                            Console.WriteLine("Successfully created THR_TERMINAL_LOGS table and index."); // For console output
                            return true;
                        }
                        catch (Exception ex)
                        {
                            transaction.Rollback();
                            LogController.Error($"Error creating table, transaction rolled back: {ex.Message}");
                            Console.WriteLine($"Error creating table, transaction rolled back: {ex.Message}"); // For console output
                            return false;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                LogController.Error($"Error connecting to Oracle DB for table creation: {ex.Message}");
                Console.WriteLine($"Error connecting to Oracle DB for table creation: {ex.Message}"); // For console output
                return false;
            }
        }

        public bool CreateProcedure()
        {
            string procedureFilePath = AppDomain.CurrentDomain.BaseDirectory + "\\HR_PRO_TRANSFER_FROM_ALPETA.sql";
            if (!System.IO.File.Exists(procedureFilePath))
            {
                LogController.Error($"Procedure file not found: {procedureFilePath}");
                Console.WriteLine($"Procedure file not found: {procedureFilePath}"); // For console output
                return false;
            }
            string procedureSql = System.IO.File.ReadAllText(procedureFilePath);
            try
            {
                using (var connection = new OracleConnection(connectionString))
                {
                    connection.Open();
                    using (var command = new OracleCommand(procedureSql.Replace("\r\n", " "), connection))
                    {
                        command.CommandType = CommandType.Text;
                        command.ExecuteNonQuery();
                    }
                }
                LogController.Information("Successfully created HR_PRO_TRANSFER_FROM_ALPETA procedure.");
                Console.WriteLine("Successfully created HR_PRO_TRANSFER_FROM_ALPETA procedure."); // For console output
                return true;
            }
            catch (Exception ex)
            {
                LogController.Error($"Error creating procedure: {ex.Message}");
                Console.WriteLine($"Error creating procedure: {ex.Message}"); // For console output
                return false;
            }
        }

        public bool EnsureTableExists()
        {
            try
            {
                if (!CheckTableExists())
                {
                    LogController.Information("THR_TERMINAL_LOGS table does not exist. Creating table...");
                    Console.WriteLine("THR_TERMINAL_LOGS table does not exist. Creating table..."); // For console output
                    return CreateTable();
                }

                return true;
            }
            catch (Exception ex)
            {
                LogController.Error($"Error ensuring table exists: {ex.Message}");
                Console.WriteLine($"Error ensuring table exists: {ex.Message}"); // For console output

                return false;
            }
        }

        public bool EnsureProcedureExists()
        {
            try
            {
                if (!CheckProcedureExist())
                {
                    LogController.Information("HR_PRO_TRANSFER_FROM_ALPETA procedure does not exist. Please create it in Oracle DB.");
                    return  CreateProcedure() ;
                }
                LogController.Information("HR_PRO_TRANSFER_FROM_ALPETA procedure exists.");
                Console.WriteLine("HR_PRO_TRANSFER_FROM_ALPETA procedure exists."); // For console output
                return true;
            }
            catch (Exception ex)
            {
                LogController.Error($"Error checking procedure existence: {ex.Message}");
                Console.WriteLine($"Error checking procedure existence: {ex.Message}"); // For console output
                return false;
            }
        }

        public bool InsertTerminalLogs(List<TerminalLog> logs)
        {
            if (logs == null || logs.Count == 0)
            {
                Console.WriteLine("No terminal logs to insert.");
                LogController.Information("No terminal logs to insert.");
                return true;
            }

            // Filter out existing logs first to improve performance
            var newLogs = FilterNewLogs(logs);
            
            if (newLogs.Count == 0)
            {
                Console.WriteLine("All logs already exist in Oracle DB. No insertion needed.");
                LogController.Information("All logs already exist in Oracle DB. No insertion needed.");
                return true;
            }

            string sql = @"
                INSERT INTO THR_TERMINAL_LOGS 
                (TERMINAL_ID, USER_ID, USER_NAME, CARD_ID, EVENT_TIME, AUTH_TYPE, AUTH_RESULT)
                VALUES 
                (:TerminalId, :UserId, :UserName, :CardId, :EventTime, :AuthType, :AuthResult)
            ";

            try
            {
                using (var connection = new OracleConnection(connectionString))
                {
                    connection.Open();
                    using (var transaction = connection.BeginTransaction())
                    {
                        try
                        {
                            using (var command = new OracleCommand(sql, connection))
                            {
                                command.Transaction = transaction;
                                
                                // Add parameters
                                command.Parameters.Add(":TerminalId", OracleDbType.Int32);
                                command.Parameters.Add(":UserId", OracleDbType.Int32);
                                command.Parameters.Add(":UserName", OracleDbType.Varchar2, 100);
                                command.Parameters.Add(":CardId", OracleDbType.Varchar2, 50);
                                command.Parameters.Add(":EventTime", OracleDbType.Date);
                                command.Parameters.Add(":AuthType", OracleDbType.Int32);
                                command.Parameters.Add(":AuthResult", OracleDbType.Int32);

                                int idx = 0;
                                foreach (var log in newLogs)
                                {
                                    command.Parameters[":TerminalId"].Value = log.TerminalId;
                                    command.Parameters[":UserId"].Value = log.UserId;
                                    command.Parameters[":UserName"].Value = log.UserName ?? "";
                                    command.Parameters[":CardId"].Value = log.CardId ?? "";
                                    command.Parameters[":EventTime"].Value = log.EventTime;
                                    command.Parameters[":AuthType"].Value = log.AuthType;
                                    command.Parameters[":AuthResult"].Value = log.AuthResult;

                                    command.ExecuteNonQuery();

                                    LogController.Information($"Inserted log: TerminalId={log.TerminalId}, UserId={log.UserId}, EventTime={log.EventTime}");

                                    Console.SetCursorPosition(0, Console.CursorTop); // Reset cursor position for console output
                                    Console.Write($"Inserted log: {++idx}/{newLogs.Count}"); // For console output
                                }
                            }

                            using (var command = new OracleCommand())
                            { 
                                command.Connection = connection;
                                command.Transaction = transaction;
                                command.CommandType = CommandType.StoredProcedure;
                                command.CommandText = "HR_PRO_TRANSFER_FROM_ALPETA"; // Call the procedure to transfer data
                                command.ExecuteNonQuery();
                                LogController.Information("Called HR_PRO_TRANSFER_FROM_ALPETA procedure to transfer data.");
                                Console.WriteLine("Called HR_PRO_TRANSFER_FROM_ALPETA procedure to transfer data."); // For console output
                            }

                            transaction.Commit();
                            Console.WriteLine($"Successfully inserted {newLogs.Count} new terminal logs to Oracle DB (filtered from {logs.Count} total logs).");
                            LogController.Information($"Successfully inserted {newLogs.Count} new terminal logs to Oracle DB (filtered from {logs.Count} total logs).");
                            return true;
                        }
                        catch (Exception ex)
                        {
                            transaction.Rollback();
                            Console.WriteLine($"Error inserting terminal logs, transaction rolled back: {ex.Message}");
                            LogController.Error($"Error inserting terminal logs, transaction rolled back: {ex.Message}");
                            throw;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error connecting to Oracle DB: {ex.Message}");
                LogController.Error($"Error connecting to Oracle DB: {ex.Message}");
                return false;
            }
        }

        public HashSet<string> GetExistingLogKeys(DateTime fromDate, DateTime toDate)
        {
            string sql = @"
                SELECT TERMINAL_ID || '|' || USER_ID || '|' || TO_CHAR(EVENT_TIME, 'YYYY-MM-DD HH24:MI:SS') as LogKey
                FROM THR_TERMINAL_LOGS
                WHERE EVENT_TIME >= :FromDate AND EVENT_TIME <= :ToDate
            ";

            HashSet<string> existingKeys = new HashSet<string>();

            try
            {
                using (var connection = new OracleConnection(connectionString))
                {
                    connection.Open();
                    using (var command = new OracleCommand(sql, connection))
                    {
                        command.Parameters.Add(":FromDate", OracleDbType.Date).Value = fromDate;
                        command.Parameters.Add(":ToDate", OracleDbType.Date).Value = toDate;

                        using (var reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                var logKey = reader["LogKey"]?.ToString();
                                if (!string.IsNullOrEmpty(logKey))
                                    existingKeys.Add(logKey);
                            }
                        }
                    }
                }

                LogController.Information($"Retrieved {existingKeys.Count} existing log keys from Oracle DB for optimization.");
                Console.WriteLine($"Retrieved {existingKeys.Count} existing log keys from Oracle DB for optimization."); // For console output
                return existingKeys;
            }
            catch (Exception ex)
            {
                LogController.Error($"Error retrieving existing log keys: {ex.Message}");
                Console.WriteLine($"Error retrieving existing log keys: {ex.Message}"); // For console output
                return new HashSet<string>();
            }
        }

        public List<TerminalLog> FilterNewLogs(List<TerminalLog> logs)
        {
            if (logs == null || logs.Count == 0)
                return new List<TerminalLog>();

            // Get date range from logs
            var minDate = logs.Min(l => l.EventTime).Date;
            var maxDate = logs.Max(l => l.EventTime).Date.AddDays(1);

            // Get existing log keys
            var existingKeys = GetExistingLogKeys(minDate, maxDate);

            // Filter out existing logs
            var newLogs = logs.Where(log =>
            {
                string logKey = $"{log.TerminalId}|{log.UserId}|{log.EventTime:yyyy-MM-dd HH:mm:ss}";
                return !existingKeys.Contains(logKey);
            }).ToList();

            LogController.Information($"Filtered {logs.Count - newLogs.Count} existing logs. {newLogs.Count} new logs to insert.");
            Console.WriteLine($"Filtered {logs.Count - newLogs.Count} existing logs. {newLogs.Count} new logs to insert."); // For console output
            return newLogs;
        }
    }
}
